# services:
#   # PostgreSQL Database
#   - type: pserv
#     name: listmonk-db
#     env: docker
#     plan: starter
#     disk:
#       name: data
#       mountPath: /var/lib/postgresql/data
#       sizeGB: 10
#     envVars:
#       - key: POSTGRES_DB
#         value: listmonk
#       - key: POSTGRES_USER
#         generateValue: true
#       - key: POSTGRES_PASSWORD
#         generateValue: true

services:
  - type: web
    name: listmonk
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: LISTMONK_db__user
        value: twosteps_db_user
      - key: LISTMONK_db__password
        value: kDCh4C4LsI2Y438GPc71S5bO7Sr3rdda
      - key: LISTMONK_db__database
        value: twosteps_db
      - key: LISTMONK_db__host
        value: dpg-d3n5bkj3fgac73abqdog-a
      - key: LISTMONK_db__port
        value: 5432
      - key: LISTMONK_db__ssl_mode
        value: disable

      # # App Settings
      # - key: LISTMONK_app__address
      #   value: 0.0.0.0:9000
      # - key: LISTMONK_app__admin_username
      #   sync: false
      # - key: LISTMONK_app__admin_password
      #   sync: false
      # - key: LISTMONK_app__cookie_secret
      #   generateValue: true
      # - key: LISTMONK_app__base_url
      #   value: https://listmonk.onrender.com

      # # Render port mapping
      # - key: PORT
      #   value: 9000